 export const mockArticle:ESObject = {
   id: "article_10",
   type: 0,
   title: "特朗普将封禁DeepSeek？外交部给出回应",
   createTime: 1751089800000,
   authorId: "author_11",
   markCount: 0,
   commentCount: 0,
   likeCount: 6000,
   shareCount: 12000,
   isLiked: false,
   isMarked: false,
   richContent:
   '\n                    <div class="content">\n                      <p style="line-height:70px;">特朗普将封禁DeepSeek？外交部给出回应</p>\n                      <p style="line-height:70px;">3 月 10 日，在外交部例行记者会上，有记者提问，据《华尔街日报》报道，美国总统特朗普正在权衡限制 DeepSeek 的措施，中方对此有何回应？</p>\n                    </p>\n                    <image class="image-preview"\n                      src="https://agc-storage-drcn.platform.dbankcloud.cn/v0/news-hnp2d/news_7.jpg"\n                      style="width: 100%;" />\n                    <p style="line-height:70px;">对此，外交部发言人毛宁表示：“我们一贯反对泛化国家安全概念，将经贸和科技问题政治化，我们也将坚定维护中国企业的合法权益。”\n                    </p>\n                    <p style="line-height:70px;">此前，自今年年初 DeepSeek 惊艳亮相、震撼世界以来，美国就一直在想方设法打压 DeepSeek，以遏制中国在人工智能技术上的发展。当地时间 1 月 28 日，美国多名官员表示 DeepSeek 是 “偷窃”，正对其影响开展国家安全调查。1 月 30 日，美国国会众议院首席行政事务官向国会办公室发出通知，警告国会办公室不要使用 DeepSeek 的服务，特朗普还称 DeepSeek 的出现 “给美国相关产业敲响了警钟” 。如今关于特朗普政府将封禁 DeepSeek 的消息传出，引发国际社会广泛关注，后续进展本报将持续跟踪报道。</p>\n                    </div>\n                  ',
   articleFrom: "1号选手",
   comments: [],
 }